<footer>
<p id="contactfooter">Contact Us</p>
<div id="btn" class="vl">
<a href="https://www.facebook.com/tunsay.tevy" class="fa fa-facebook"></a>
<a href="https://youtu.be/dQw4w9WgXcQ" class="fa fa-youtube"></a>
<a href="https://www.instagram.com/novemberry__/" class="fa fa-instagram"></a>	
</div>
<div id="email">
<strong>Email:</strong><a href="mailto:103139978@student.swin.edu.au"><br /> JRT@gmail.com</a>
</div>
<div id="phone" class="vl"><strong>Phone:</strong><br />(+855)78-464096 <br />(+855)78-464099</div>
</footer>
</body>